### ISSUE TITLE
Error - code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by tatchi** [zaiste/huncwot-todo-graphql#1]
Hello,

I cloned the repo, installed huncwot globally and then run `yarn `to install the dependencies. When I start the application with `huncwot server` I get the following error message:

> C:\Users\clt\Documents\Projects\huncwot-todo-graphql>huncwot server
Huncwot: Server running at http://localhost:5544
{ Error: Cannot find module 'C:\Users\clt\Documents\Projects\huncwot-todo-graphql\pages\index.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at init (C:\Users\clt\AppData\Local\Yarn\config\global\node_modules\huncwot\cli\server.js:81:18)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (
see docs http://knexjs.org/#Builder-insert).

Any ideas of what could be the issue? :)

**Comment by zaiste** [comment]
@tatchi it's a known issue :) It's nothing serious. I'm refactoring the main CLI mechanism currently. You can create an empty `index.js` in `pages` to get rid of it. This error shouldn't have any impact on the rest of the application. I'll fix it this week!

**Comment by tatchi** [comment]
It works 👍 

Thanks :)
